name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  native_gem:
    name: Compile native gem
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - x86_64-linux
          - x86_64-linux-musl
          - aarch64-linux
          - arm-linux
          - x86_64-darwin
          - arm64-darwin
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby & Rust
      uses: oxidize-rb/actions/setup-ruby-and-rust@main
      with:
        ruby-version: '3.1'
        bundler-cache: true
        cargo-cache: true
        rubygems: '3.4.7'
    - name: Run the default task
      run: bundle exec rake
    - name: cross-gem
      uses: oxidize-rb/cross-gem-action@v7
      with:
        platform: ${{ matrix.platform }}
        version: 'latest'
        ruby-versions: '3.0, 3.1, 3.2'
    - uses: actions/download-artifact@v3
      with:
        name: cross-gem
        path: pkg/
    - name: Display structure of built gems
      run: ls -R
      working-directory: pkg/

